import type { CaseItem, StaffMember, Timeline, Notification, BankTransaction, FinanceEntry, ApprovalDoc, DashboardStats, ConsultationItem, ConsultationRoom } from "./types";

export const mockStaff: StaffMember[] = [
  { id: "s1", name: "김민준", role: "변호사", department: "형사부", email: "minjun@lawfirm.com", phone: "010-1234-5678", level: 4 },
  { id: "s2", name: "이서연", role: "변호사", department: "민사부", email: "seoyeon@lawfirm.com", phone: "010-2345-6789", level: 3 },
  { id: "s3", name: "박지훈", role: "사무장", department: "행정팀", email: "jihoon@lawfirm.com", phone: "010-3456-7890", level: 2 },
  { id: "s4", name: "최연진", role: "사무원", department: "형사부", email: "yeonjin@lawfirm.com", phone: "010-4567-8901", level: 1 },
  { id: "s5", name: "정수경", role: "사무원", department: "민사부", email: "sukyung@lawfirm.com", phone: "010-5678-9012", level: 1 },
  { id: "s6", name: "강이소", role: "인턴", department: "형사부", email: "iso@lawfirm.com", phone: "010-6789-0123", level: 0 },
];

const today = new Date();
const addDays = (d: number) => {
  const dt = new Date(today);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString().split("T")[0];
};

export const mockCases: CaseItem[] = [
  {
    id: "c001",
    caseNumber: "2026노107",
    caseType: "형사",
    caseName: "특수상해",
    court: "서울고등법원",
    clientName: "이창우",
    clientPosition: "피고인",
    opponentName: "검사",
    status: "진행중",
    assignedStaff: "김민준",
    assistants: "최연진, 정수경, 강이소",
    nextDate: addDays(0),
    nextDateType: "선고기일",
    isElectronic: true,
    isUrgent: true,
    isImmutable: true,
    receivedDate: "2026-01-15",
    amount: 5000000,
    receivedAmount: 3000000,
    pendingAmount: 2000000,
    notes: "항소심 진행중. 증거 보강 필요.",
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-03-04T14:30:00Z",
  },
  {
    id: "c002",
    caseNumber: "2025가합3421",
    caseType: "민사",
    caseName: "손해배상청구",
    court: "서울중앙지방법원",
    clientName: "주식회사 테크원",
    clientPosition: "원고",
    opponentName: "홍길동",
    status: "진행중",
    assignedStaff: "이서연",
    assistants: "정수경",
    nextDate: addDays(2),
    nextDateType: "변론기일",
    isElectronic: true,
    isUrgent: true,
    isImmutable: false,
    receivedDate: "2025-08-10",
    amount: 10000000,
    receivedAmount: 5000000,
    pendingAmount: 5000000,
    notes: "계약서 원본 제출 필요.",
    createdAt: "2025-08-10T10:00:00Z",
    updatedAt: "2026-03-03T11:20:00Z",
  },
  {
    id: "c003",
    caseNumber: "2026카기551",
    caseType: "민사",
    caseName: "부동산가처분",
    court: "인천지방법원",
    clientName: "박성철",
    clientPosition: "채권자",
    opponentName: "김영호",
    status: "진행중",
    assignedStaff: "이서연",
    assistants: "정수경, 강이소",
    nextDate: addDays(3),
    nextDateType: "심문기일",
    isElectronic: false,
    isUrgent: true,
    isImmutable: false,
    receivedDate: "2026-02-20",
    amount: 3000000,
    receivedAmount: 3000000,
    pendingAmount: 0,
    notes: "가처분 인용 결정 예상.",
    createdAt: "2026-02-20T09:30:00Z",
    updatedAt: "2026-03-02T16:45:00Z",
  },
  {
    id: "c004",
    caseNumber: "2025고단8821",
    caseType: "형사",
    caseName: "사기",
    court: "수원지방법원",
    clientName: "최민서",
    clientPosition: "피고인",
    opponentName: "검사",
    status: "진행중",
    assignedStaff: "김민준",
    assistants: "최연진",
    nextDate: addDays(7),
    nextDateType: "공판기일",
    isElectronic: true,
    isUrgent: false,
    isImmutable: false,
    receivedDate: "2025-11-05",
    amount: 8000000,
    receivedAmount: 8000000,
    pendingAmount: 0,
    notes: "증인 신청서 준비 완료.",
    createdAt: "2025-11-05T14:00:00Z",
    updatedAt: "2026-02-28T09:10:00Z",
  },
  {
    id: "c005",
    caseNumber: "2026나12045",
    caseType: "민사",
    caseName: "임금청구",
    court: "서울동부지방법원",
    clientName: "노동조합 연대",
    clientPosition: "원고",
    opponentName: "주식회사 한국물류",
    status: "진행중",
    assignedStaff: "이서연",
    assistants: "정수경",
    nextDate: addDays(10),
    nextDateType: "변론기일",
    isElectronic: false,
    isUrgent: false,
    isImmutable: false,
    receivedDate: "2026-01-08",
    amount: 15000000,
    receivedAmount: 7500000,
    pendingAmount: 7500000,
    notes: "집단소송. 원고 30명.",
    createdAt: "2026-01-08T11:00:00Z",
    updatedAt: "2026-03-01T13:00:00Z",
  },
  {
    id: "c006",
    caseNumber: "2025헌마422",
    caseType: "헌법",
    caseName: "위헌법률심판",
    court: "헌법재판소",
    clientName: "시민단체 정의연대",
    clientPosition: "청구인",
    opponentName: "국가",
    status: "보류",
    assignedStaff: "김민준",
    assistants: "강이소",
    nextDate: addDays(30),
    nextDateType: "공개변론",
    isElectronic: true,
    isUrgent: false,
    isImmutable: false,
    receivedDate: "2025-09-15",
    amount: 20000000,
    receivedAmount: 10000000,
    pendingAmount: 10000000,
    notes: "보충서면 제출 예정.",
    createdAt: "2025-09-15T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "c007",
    caseNumber: "2025가소12304",
    caseType: "민사",
    caseName: "대여금반환청구",
    court: "서울남부지방법원",
    clientName: "황지수",
    clientPosition: "원고",
    opponentName: "김대현",
    status: "완료",
    assignedStaff: "이서연",
    assistants: "정수경",
    nextDate: null,
    nextDateType: "",
    isElectronic: false,
    isUrgent: false,
    isImmutable: false,
    receivedDate: "2025-06-01",
    amount: 2000000,
    receivedAmount: 2000000,
    pendingAmount: 0,
    notes: "승소 확정 판결.",
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2026-01-15T16:00:00Z",
  },
  {
    id: "c008",
    caseNumber: "2026초기112",
    caseType: "형사",
    caseName: "명예훼손",
    court: "서울중앙지방법원",
    clientName: "유명인 A씨",
    clientPosition: "고소인",
    opponentName: "블로거 B씨",
    status: "진행중",
    assignedStaff: "김민준",
    assistants: "최연진, 강이소",
    nextDate: addDays(14),
    nextDateType: "진술기일",
    isElectronic: true,
    isUrgent: false,
    isImmutable: false,
    receivedDate: "2026-02-10",
    amount: 5000000,
    receivedAmount: 2500000,
    pendingAmount: 2500000,
    notes: "증거자료 스크린샷 수집 완료.",
    createdAt: "2026-02-10T10:30:00Z",
    updatedAt: "2026-03-04T09:00:00Z",
  },
];

export const mockTimeline: Timeline[] = [
  {
    id: "t1",
    caseId: "c001",
    type: "memo",
    title: "의뢰인 상담 메모",
    content: "의뢰인 이창우 씨 오늘 오전 방문. 항소 이유서 보충 자료 추가 제출하기로 함. 피해자와 합의 가능성 타진 중.",
    authorId: "s1",
    authorName: "김민준",
    date: "2026-03-04T14:30:00Z",
  },
  {
    id: "t2",
    caseId: "c001",
    type: "court_update",
    title: "서울고등법원 - 기일 통지",
    content: "선고기일이 2026-03-05로 지정됨. 오전 10시 제11형사부.",
    authorId: "system",
    authorName: "법원 시스템",
    date: "2026-03-01T09:00:00Z",
  },
  {
    id: "t3",
    caseId: "c001",
    type: "document",
    title: "항소이유서 최종본 업로드",
    content: "2026년 3월 제출용 항소이유서 최종 버전 업로드 완료.",
    authorId: "s4",
    authorName: "최연진",
    date: "2026-02-28T16:45:00Z",
    attachments: [
      { id: "f1", fileName: "항소이유서_최종_20260228.pdf", fileSize: 1048576, mimeType: "application/pdf", url: "#" },
      { id: "f2", fileName: "증거자료_목록.xlsx", fileSize: 15360, mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", url: "#" },
    ],
  },
  {
    id: "t4",
    caseId: "c001",
    type: "finance",
    title: "수임료 수납",
    content: "2차 수임료 1,000,000원 수납 완료.",
    authorId: "s3",
    authorName: "박지훈",
    date: "2026-02-15T10:00:00Z",
    metadata: { amount: 1000000, type: "수납" },
  },
  {
    id: "t5",
    caseId: "c001",
    type: "status_change",
    title: "상태 변경: 1심 종결 → 항소심 진행",
    content: "1심 징역 2년 판결 후 항소 제기. 항소심 진행 상태로 변경됨.",
    authorId: "s1",
    authorName: "김민준",
    date: "2026-01-20T11:30:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "urgent_date",
    title: "오늘 선고기일 - 이창우 사건",
    message: "2026노107 특수상해 사건 오전 10시 서울고등법원 제11형사부",
    isRead: false,
    caseId: "c001",
    createdAt: new Date().toISOString(),
    link: "/cases/c001",
  },
  {
    id: "n2",
    type: "approval_request",
    title: "결재 요청 - 손해배상청구 보고서",
    message: "이서연 변호사가 결재를 요청했습니다.",
    isRead: false,
    caseId: "c002",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    link: "/approval",
  },
  {
    id: "n3",
    type: "finance",
    title: "미수금 알림 - 테크원 사건",
    message: "2025가합3421 사건 미수금 5,000,000원이 30일 경과했습니다.",
    isRead: true,
    caseId: "c002",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    link: "/finance",
  },
];

export const mockBankTransactions: BankTransaction[] = [
  { id: "bt1", date: addDays(-1), depositorName: "이창우", amount: 1000000, bankName: "국민은행", memo: "수임료 2차", matchedTo: undefined },
  { id: "bt2", date: addDays(-2), depositorName: "테크원", amount: 2000000, bankName: "신한은행", memo: "손해배상건", matchedTo: undefined },
  { id: "bt3", date: addDays(-3), depositorName: "박성철", amount: 500000, bankName: "우리은행", memo: "가처분", matchedTo: undefined },
  { id: "bt4", date: addDays(-1), depositorName: "노동조합연대", amount: 3000000, bankName: "기업은행", memo: "임금청구 착수금", matchedTo: undefined },
];

export const mockFinanceEntries: FinanceEntry[] = [
  { id: "fe1", type: "미수금", caseId: "c001", caseNumber: "2026노107", clientName: "이창우", amount: 2000000, date: "2026-02-01", description: "잔여 수임료", status: "미확인" },
  { id: "fe2", type: "미수금", caseId: "c002", caseNumber: "2025가합3421", clientName: "주식회사 테크원", amount: 5000000, date: "2026-01-15", description: "2차 착수금", status: "미확인" },
  { id: "fe3", type: "미수금", caseId: "c005", caseNumber: "2026나12045", clientName: "노동조합 연대", amount: 7500000, date: "2026-02-08", description: "착수금 잔액", status: "미확인" },
  { id: "fe4", type: "수납", caseId: "c004", caseNumber: "2025고단8821", clientName: "최민서", amount: 8000000, date: "2025-11-10", description: "전액 수납", status: "확인" },
];

export const mockApprovals: ApprovalDoc[] = [
  {
    id: "ap1",
    title: "2025가합3421 손해배상 착수금 청구서",
    type: "청구서",
    status: "결재요청",
    caseId: "c002",
    caseNumber: "2025가합3421",
    requesterId: "s2",
    requesterName: "이서연",
    amount: 5000000,
    approvalLine: [
      { order: 1, staffId: "s3", staffName: "박지훈", role: "사무장", status: "승인", signedAt: new Date().toISOString() },
      { order: 2, staffId: "s1", staffName: "김민준", role: "대표변호사", status: "대기" },
    ],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    notes: "2차 착수금 청구 요청입니다.",
  },
  {
    id: "ap2",
    title: "2026노107 특수상해 변호인 선임동의서",
    type: "기타",
    status: "결재완료",
    caseId: "c001",
    caseNumber: "2026노107",
    requesterId: "s2",
    requesterName: "이서연",
    approvalLine: [
      { order: 1, staffId: "s3", staffName: "박지훈", role: "사무장", status: "승인", signedAt: new Date().toISOString() },
      { order: 2, staffId: "s1", staffName: "김민준", role: "대표변호사", status: "승인", signedAt: new Date().toISOString() },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    attachmentNames: ["선임동의서.pdf", "의견서.docx"],
  },
  {
    id: "ap3",
    title: "2025가합3421 손해배상 2차 착수금 청구서",
    type: "청구서",
    status: "결재완료",
    caseId: "c002",
    caseNumber: "2025가합3421",
    requesterId: "s2",
    requesterName: "이서연",
    amount: 3000000,
    approvalLine: [
      { order: 1, staffId: "s3", staffName: "박지훈", role: "사무장", status: "승인", signedAt: new Date().toISOString() },
      { order: 2, staffId: "s1", staffName: "김민준", role: "대표변호사", status: "승인", signedAt: new Date().toISOString() },
    ],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    attachmentNames: ["착수금청구서.pdf"],
  },
  {
    id: "ap4",
    title: "2025고단8821 사기 사건 수임계약서",
    type: "계약서",
    status: "결재완료",
    caseId: "c004",
    caseNumber: "2025고단8821",
    requesterId: "s1",
    requesterName: "김민준",
    approvalLine: [
      { order: 1, staffId: "s3", staffName: "박지훈", role: "사무장", status: "승인", signedAt: new Date().toISOString() },
      { order: 2, staffId: "s1", staffName: "김민준", role: "대표변호사", status: "승인", signedAt: new Date().toISOString() },
    ],
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    attachmentNames: ["수임계약서.pdf", "비밀유지각서.pdf"],
  },
];

export const mockDashboardStats: DashboardStats = {
  todayDeadlines: 1,
  urgentCases: 3,
  pendingApprovals: 2,
  pendingPayments: 3,
  totalActiveCases: 6,
  totalMonthlyIncome: 12500000,
};

/** 상담실 (회의실 등록/편집에 대응) */
export const mockConsultationRooms: ConsultationRoom[] = [
  { id: "r1", name: "902호(대회의실)", sortOrder: 1, remarks: "대형 상담" },
  { id: "r2", name: "1005호(소회의실)", sortOrder: 2, remarks: "1:1 상담" },
  { id: "r3", name: "1007호(중회의실)", sortOrder: 3 },
  { id: "r4", name: "1307호(소회의실)", sortOrder: 4 },
];

/** 상담 일정·기록 (캘린더 연동, 매치사건 연동) */
export const mockConsultations: ConsultationItem[] = [
  {
    id: "con1",
    consultationDate: addDays(0),
    startTime: "10:00",
    endTime: "10:30",
    roomId: "r1",
    roomName: "902호(대회의실)",
    consultantId: "s1",
    consultantName: "김민준",
    clientName: "이창우",
    purpose: "형사 사건 상담",
    importance: "high",
    status: "notified",
    caseId: "c001",
    caseNumber: "2026노107",
    notes: "선고기일 전 상담",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "con2",
    consultationDate: addDays(0),
    startTime: "14:00",
    endTime: "14:30",
    roomId: "r2",
    roomName: "1005호(소회의실)",
    consultantId: "s2",
    consultantName: "이서연",
    clientName: "주식회사 테크원",
    purpose: "민사 상담",
    importance: "medium",
    status: "scheduled",
    caseId: "c002",
    caseNumber: "2025가합3421",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "con3",
    consultationDate: addDays(1),
    startTime: "09:30",
    endTime: "10:00",
    roomId: "r2",
    roomName: "1005호(소회의실)",
    consultantId: "s1",
    consultantName: "김민준",
    clientName: "홍길동",
    purpose: "신규 상담",
    importance: "low",
    status: "scheduled",
    notes: "초회 상담",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
